alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
features:
  - buildpack-stack=ubuntu-22
ingress:
  rules:
    - component:
        name: maiempire-go-sample-app
      match:
        path:
          prefix: /
name: go-sample-app
region: fra
services:
  - envs:
      - key: PORT
        scope: RUN_AND_BUILD_TIME
        value: "${PORT}"
      - key: DB_HOST
        scope: RUN_AND_BUILD_TIME
        value: "${DB_HOST}"
      - key: DB_PORT
        scope: RUN_AND_BUILD_TIME
        value: "${DB_PORT}"
      - key: DB_NAME
        scope: RUN_AND_BUILD_TIME
        value: "${DB_NAME}"
      - key: DB_USER
        scope: RUN_AND_BUILD_TIME
        value: "${DB_USER}"
      - key: DB_PASSWORD
        scope: RUN_AND_BUILD_TIME
        value: "${DB_PASSWORD}"
    http_port: 8080
    image:
      registry: maiempire
      registry_type: DOCKER_HUB
      repository: go-sample-app
      tag: v2
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    name: maiempire-go-sample-app